### ISSUE TITLE
Violation of the CCEmuX licence

### ISSUE THREAD

**Issue by Lignum** [CoolMan119/coolman119.github.io#1]
Your website violates the CCEmuX licence by incorrectly distributing it [here](http://coolman119.github.io/downloads/CCEmuX-1.0-SNAPSHOT.jar).
Specifically, you are infringing on this paragraph:

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

([Source](https://raw.githubusercontent.com/Lignumm/CCEmuX/64709c3240b8963110e4bf95844c2675a1315949/LICENCE.txt))

Either add the licence somewhere or take down the download.

**Comment by CoolMan119** [comment]
I will add the license, I'm sorry that I have not included the license, it will be included in `CCEmuX-License.txt` if you're okay with it, please tell me if you're not.

**Comment by Lignum** [comment]
Yes, this is ok. Thanks.

**Comment by CoolMan119** [comment]
No problem.
